# Generated by Django 4.2.2 on 2023-07-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(max_length=150, verbose_name='نام انبار'),
        ),
    ]
