# Generated by Django 4.2.2 on 2023-07-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_inventory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('در حال بررسی', 'در حال بررسی'), ('تایید شده', 'تایید شده'), ('عدم تایید', 'عدم تایید')], default='در حال بررسی', max_length=20, verbose_name='وضعیت'),
        ),
    ]
